import { performance } from "node:perf_hooks";
const mb = (b: number) => (b / 1048576).toFixed(0) + "MB";
console.log(`start rss ${mb(process.memoryUsage().rss)}`);
let t = performance.now();
await import("@huggingface/transformers");
console.log(`import @huggingface/transformers (+ onnxruntime-node + sharp) ${(performance.now() - t).toFixed(0)} ms, rss ${mb(process.memoryUsage().rss)}`);
t = performance.now();
await import("@codegenie/serverless-express");
await import("express");
console.log(`import serverless-express + express ${(performance.now() - t).toFixed(0)} ms`);
t = performance.now();
const { createConfiguredApp } = await import("/Users/chrismiho/Coding/Projects/TheJudge/apps/backend/src/runtime/createConfiguredApp.ts");
const { readServerConfig } = await import("/Users/chrismiho/Coding/Projects/TheJudge/apps/backend/src/config/index.ts");
const { createEmbeddingProvider } = await import("/Users/chrismiho/Coding/Projects/TheJudge/apps/backend/src/providers/createEmbeddingProvider.ts");
console.log(`import backend modules ${(performance.now() - t).toFixed(0)} ms`);
const env = { ...process.env, ASK_AI_PROVIDER: "mock", NODE_ENV: "production", EMBEDDING_PROVIDER: "local" } as NodeJS.ProcessEnv;
t = performance.now();
createConfiguredApp("/Users/chrismiho/Coding/Projects/TheJudge", env);
console.log(`createConfiguredApp once ${(performance.now() - t).toFixed(0)} ms, rss ${mb(process.memoryUsage().rss)}`);
t = performance.now();
await createEmbeddingProvider(readServerConfig(env)).embed("warm the model");
console.log(`first embed ${(performance.now() - t).toFixed(0)} ms, rss ${mb(process.memoryUsage().rss)}, heapUsed ${mb(process.memoryUsage().heapUsed)}`);
